### ISSUE TITLE
RoadMap [Alpha]

### ISSUE THREAD

**Issue by willin** [loglu/log.lu#1]
- [ ] Overall:  Static Team Blog
- [ ] Feature
    - [ ] Word count （Total / Author / Category / Tag / Post）
    - [ ] Github latest team contributions, rank of project stars
    - [ ] Algolia Search
- [ ] Template
    - [ ] Post List
    - [ ] Archive
    - [ ] Category
    - [ ] Tag
    - [ ] Post / Page
    - [ ] Author
- [ ] Theme
    - [ ] Animations
        - [ ] Loading (Page / Content / Component)
        - [ ] ScrollSpy (for TOC)
        - [ ] Page transition
    - [ ] Dark Mode
    - [ ] Highlight of codes
    - [ ] Image lazy load and overlay (like Lightbox plugin)
- [ ] SEO & Improvement
    - [ ] Sitemap
    - [ ] RSS Feed
    - [ ] Service Worker
    - [ ] Google AMP
